version: '3.8'

services:

  inference:
    depends_on:
      - kafka
    build:
      dockerfile: inference.Dockerfile
      context: .
    image: inference
    devices:
      - /dev/video0:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    volumes:
      - "./.build/capture:/tmp/capture"
      - "./src:/application/src"
    container_name: inference
    ports:
      - "127.0.0.1:5001:80"
    restart: always

  kafka:
    container_name: kafka
    restart: unless-stopped
    build:
      dockerfile: kafka.Dockerfile
      context: .
    ports:
      - "9092:9092"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.build/kafka-server.properties:/opt/kafka/config/server.properties"
      - "./.build/zookeeper.properties:/opt/kafka/config/zookeeper.properties"

  kafkacat:
    depends_on:
      - kafka
    container_name: kafkacat
    restart: unless-stopped
    image: confluentinc/cp-kafkacat:latest
    command: bash -c "kafkacat -b kafka:9092 -t test -C"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"